### PR TITLE
Fix boost include dirs

### PR DESCRIPTION
**Pull request by tammojan**
If boost is installed in a non-standard location, but boost headers are available in a system dir (e.g. `/usr/include`) building may work, but at runtime a symbol may not be found. This commit guesses the include directory from the found boost library, and passes that include directory to the build process.

We should really move away from boost_python...

### CODE REVIEW

**Comment by tammojan** [comment]
@darafferty Could you have a look at this? Somehow the python3.5 test now segfaults (the button still shows green because it's an 'allowed failure').

**Comment by darafferty** [comment]
I got the python 3.5 test to run successfully, but I had to retry it a few times (setting ncores=2 in my last commit might have helped, not sure).

**Comment by tammojan** [comment]
@darafferty If you agree with the change, could you merge this? I think the segfault is unrelated to the change.

**Comment by darafferty** [comment]
Yep, agreed.

**Pull request merged**
